
//	OOPS Concepts

/////////////////////////////////////////////////////////////////////////////////////
//
//	Oops Concept 	:	Constructors
//
//	Default Constructor : Constructor generated by Compiler 
//	-------------------------
//	2. Parameterized Constructor
//		:	if we pass atleast one arg to userdefined constructor
//
//	What is Constructor Overloading
//	Same Constructor name with diff. parameters in a single class
//
/////////////////////////////////////////////////////////////////////////////////////

class OOPS_ConstructorOverloading
{
	OOPS_ConstructorOverloading()
	{
		System.out.println("Zero arg Constructor");
	}

	OOPS_ConstructorOverloading(int i)
	{
		System.out.println("With int-arg Constructor");
	}

	OOPS_ConstructorOverloading(double d)
	{
		System.out.println("With  double-arg Constructor");
	}

	public static void main(String[] args)
	{
		OOPS_ConstructorOverloading obj1 = new OOPS_ConstructorOverloading();

		OOPS_ConstructorOverloading obj2 = new OOPS_ConstructorOverloading(10);

		OOPS_ConstructorOverloading obj3 = new OOPS_ConstructorOverloading(10000d);

	}
}


//////////////////////////////////////////////////////////////////////
//
//	Output	:	Zero arg Constructor
//				With int-arg Constructor
//				With  double-arg Constructor
//
//////////////////////////////////////////////////////////////////////
