
//	OOPS Concepts

/////////////////////////////////////////////////////////////////////////////////////
//
//	Oops Concept 	:	Constructors
//
//	Default Constructor : Constructor generated by Compiler 
//	-------------------------
//	2. Parameterized Constructor
//		:	if we pass atleast one arg to userdefined constructor
//
/////////////////////////////////////////////////////////////////////////////////////

class OOPS_DefaultConstructor
{

	public static void main(String[] args)
	{
		System.out.println("Default");
		System.out.println("Hello");
	}
}


//////////////////////////////////////////////////////////////////////
//
//	Command	:	javac OOPS_DefaultConstructor.java
//			:	javap -c OOPS_DefaultConstructor
//
//	Output	:	OOPS_DefaultConstructor();
//				// String Default
//				// String Hello
//
//////////////////////////////////////////////////////////////////////
